index:
    pattern : /
    defaults : { _controller: SecurinetsFrontOfficeBundle:Default:index}

home:
    pattern:  /home
    defaults: { _controller: SecurinetsFrontOfficeBundle:Default:home}

getRules:
    pattern: /getRules
    defaults: { _controller: SecurinetsFrontOfficeBundle:Default:getRules }

getTasks:
    pattern: /getTasks
    defaults: { _controller: SecurinetsFrontOfficeBundle:Challenge:getTasks }

validate:
    pattern : /validate/epreuve/{id}
    defaults: { _controller: SecurinetsFrontOfficeBundle:Challenge:validate , id : 0}
    requirements:
        id : \d+

score:
    pattern: /score
    defaults : { _controller: SecurinetsFrontOfficeBundle:Challenge:score }

erreurConnexion:
    pattern: /erreurConnexion
    defaults : { _controller: SecurinetsFrontOfficeBundle:Challenge:erreurConnexion }

getRemaingTime:
    pattern: /getRemaingTime
    defaults: { _controller: SecurinetsFrontOfficeBundle:Chrono:remaingTime}

getTask:
    pattern : /getTask/{id_epreuve}
    defaults: { _controller: SecurinetsFrontOfficeBundle:Challenge:getTask,id_epreuve : 0}
    requirements:
        id : \d+

countDown:
    pattern : /countDown
    defaults: {  _controller: SecurinetsFrontOfficeBundle:Default:countDown } 

challengerInfo:
    pattern : /challengerInfo
    defaults : {  _controller: SecurinetsFrontOfficeBundle:Challenge:challengerInfo }

getNews:
    pattern : /getNews
    defaults : { _controller : SecurinetsFrontOfficeBundle:Challenge:getNews }